
# Header
language: r
r:
  - release 3.2
sudo: false
dist: trusty
cache: packages
warnings_are_errors: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

r_packages:
  - minpack.lm
  - nloptr
  - knitr
  - rmarkdown
  - devtools
  - testthat
  - covr

email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e "library(covr); codecov(token = '9e2041f6-3c11-42e8-adb8-7fbe31abe822')"
