sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - minpack.lm
  - nloptr
  - plyr
  - pryr
  - knitr
  - rmarkdown
  - devtools
  - testthat
  - shiny
  - covr

email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
